# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'PhoneKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneKitDemo

    pod "PhoneKit", :git => 'https://github.com/nevermore-imba/PhoneKit.git'
    pod "AFNetworking"

end
